# Generated by Django 2.2.3 on 2019-07-06 07:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('address', models.CharField(max_length=200, verbose_name='Customer Address')),
                ('contact_person', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('GST', models.CharField(max_length=50)),
                ('credit_period', models.IntegerField(verbose_name='Credit Period in Days')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50, verbose_name='Product Name')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseData',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('supplier', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('in_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subproduct', models.CharField(max_length=50, verbose_name='Sub Product Name')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=50, verbose_name='Vendor Name')),
                ('address', models.CharField(max_length=200, verbose_name='Vendor Address')),
                ('contact_person', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('GST', models.CharField(max_length=50)),
                ('credit_period', models.IntegerField(verbose_name='Credit Period in Days')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VendorData',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False, verbose_name='Sr No')),
                ('out_date', models.DateField(verbose_name='Out Date')),
                ('material_provided', models.CharField(max_length=50, verbose_name='Material Provided / Part Name')),
                ('quantity', models.IntegerField(verbose_name='Quantity Provided')),
                ('purpose', models.CharField(max_length=50)),
                ('quantity_received', models.IntegerField(verbose_name='Quantity Received')),
                ('in_date', models.DateField(verbose_name='In Date')),
                ('vendor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Vendor', verbose_name='Vendor Name')),
            ],
        ),
        migrations.CreateModel(
            name='Subsubproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsubproduct', models.CharField(max_length=50, verbose_name=' Sub Sub Product Name')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Product')),
                ('subproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Subproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_no', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date (YYYY-MM-DD)')),
                ('end_date', models.IntegerField(verbose_name='End Date (YYYYMMDD)')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Product')),
                ('subproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Subproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=50)),
                ('raw_material', models.CharField(max_length=50)),
                ('specs_1', models.CharField(max_length=50)),
                ('specs_2', models.CharField(max_length=50)),
                ('specs_3', models.CharField(max_length=50)),
                ('source_1', models.CharField(max_length=50)),
                ('source_2', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('lead_time', models.CharField(max_length=20)),
                ('vendor', models.CharField(max_length=20)),
                ('inventory', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Product')),
                ('subproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Subproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False, verbose_name='Sr No')),
                ('date', models.DateField(verbose_name='Date')),
                ('part_name', models.CharField(max_length=50, verbose_name='Part Name')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('misc', models.CharField(max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Worker', verbose_name='Worker Name')),
            ],
        ),
    ]
