# Generated by Django 2.2.3 on 2019-07-06 10:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toggle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toggle', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='in_date',
            field=models.DateField(verbose_name='In Date (YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='vendordata',
            name='out_date',
            field=models.DateField(verbose_name='Out Date (YYYY-MM-DD)'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Worker', verbose_name='Worker Name')),
                ('toggle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Toggle', verbose_name='Worker Name')),
            ],
        ),
    ]
